"""
Doc Writer Agent - Synthesizes comprehensive Developer Guides, Markdown Docs, and Postman Collections.
Syllabus Alignment: Unit 2 (Writer Agent, Executive-Ready Report) & Unit 5 (Structured Outputs).
"""

import json
import time
from typing import Any, Dict
from .base_agent import BaseAgent
from ..tools.curl_generator import CurlGeneratorTool


class DocWriterAgent(BaseAgent):
    """Specialist agent responsible for human-centric documentation and multi-language SDK snippets."""

    def __init__(self, model_provider: str = "auto"):
        super().__init__(
            name="DocWriterAgent",
            role="Lead Technical Documentation Author",
            goal="Compose publication-grade developer documentation, multi-language client snippets, and API testing suites.",
            backstory="A developer advocate passionate about clear documentation, SDK onboarding, and intuitive developer portals.",
            tools=[CurlGeneratorTool()],
            model_provider=model_provider
        )
        self.snippet_generator = CurlGeneratorTool()

    def execute(self, state: Dict[str, Any]) -> Dict[str, Any]:
        start_time = time.time()
        spec = state.get("openapi_spec", {})
        endpoints = state.get("endpoints", [])
        audit_report = state.get("audit_report", {})
        title = spec.get("info", {}).get("title", "RESTful API Service")
        version = spec.get("info", {}).get("version", "1.0.0")
        description = spec.get("info", {}).get("description", "")
        servers = spec.get("servers", [{"url": "http://localhost:8000"}])
        base_url = servers[0]["url"] if servers else "http://localhost:8000"

        # 1. Build Markdown Developer Portal Documentation
        md_lines = [
            f"# {title} - Developer API Documentation",
            "",
            f"**Version**: `{version}` | **OpenAPI**: `3.1.0` | **Generated by**: *Automated API Documentation Assistant*",
            "",
            "## 📖 Overview",
            description,
            "",
            "### Base Servers",
        ]
        for s in servers:
            md_lines.append(f"- **`{s.get('url')}`**: {s.get('description', 'API Server')}")

        md_lines.extend([
            "",
            "---",
            "",
            "## 🔐 Authentication & Authorization",
            "This API utilizes **HTTP Bearer Tokens (JWT)** for protected endpoints.",
            "Include your token in the `Authorization` header:",
            "```http",
            "Authorization: Bearer <YOUR_ACCESS_TOKEN>",
            "```",
            "",
            "---",
            "",
            "## 🚀 Endpoint Reference Summary",
            "",
            "| Method | Endpoint Path | Summary | Auth Required | Tags |",
            "| :--- | :--- | :--- | :---: | :--- |"
        ])

        for ep in endpoints:
            m = ep.get("method", "GET").upper()
            p = ep.get("path", "/")
            s = ep.get("summary", "")
            auth = "🔒 Yes" if ep.get("auth_required") else "🔓 No"
            tags = ", ".join(ep.get("tags", []))
            md_lines.append(f"| `{m}` | `{p}` | {s} | {auth} | {tags} |")

        md_lines.extend(["", "---", "", "## 📘 Detailed Endpoint Documentation", ""])

        for ep in endpoints:
            m = ep.get("method", "GET").upper()
            p = ep.get("path", "/")
            s = ep.get("summary", "")
            d = ep.get("description", "")
            params = ep.get("parameters", [])
            req_body = ep.get("request_body")
            responses = ep.get("responses", {})
            snippets = self.snippet_generator.generate_snippets(ep, base_url=base_url)

            md_lines.extend([
                f"### `{m}` {p}",
                f"**Summary**: {s}",
                "",
                f"**Description**: {d}",
                ""
            ])

            if params:
                md_lines.extend([
                    "#### Parameters",
                    "",
                    "| Parameter | Location | Type | Required | Description |",
                    "| :--- | :--- | :--- | :---: | :--- |"
                ])
                for param in params:
                    req_badge = "**Yes**" if param.get("required") else "No"
                    md_lines.append(f"| `{param.get('name')}` | `{param.get('in')}` | `{param.get('type')}` | {req_badge} | {param.get('description', '-')} |")
                md_lines.append("")

            if req_body:
                md_lines.extend([
                    "#### Request Body",
                    f"- **Content-Type**: `{req_body.get('content_type', 'application/json')}`",
                    f"- **Schema Model**: `{req_body.get('schema_name', 'RequestBody')}`",
                    ""
                ])

            md_lines.extend([
                "#### Expected Responses",
                "",
                "| Status Code | Description | Content Type |",
                "| :--- | :--- | :--- |"
            ])
            for code, resp in responses.items():
                md_lines.append(f"| `{code}` | {resp.get('description', '-')} | `application/json` |")
            md_lines.append("")

            md_lines.extend([
                "#### Code Examples",
                "",
                "**cURL Command**:",
                "```bash",
                snippets["curl"],
                "```",
                "",
                "**Python (`requests`)**:",
                "```python",
                snippets["python"],
                "```",
                "",
                "**JavaScript (`fetch`)**:",
                "```javascript",
                snippets["javascript"],
                "```",
                "",
                "---",
                ""
            ])

        # Security Findings Section
        sec_findings = audit_report.get("security_findings", [])
        if sec_findings:
            md_lines.extend([
                "## 🛡️ Security Audit & OWASP API Recommendations",
                f"**OWASP Security Score**: `{audit_report.get('security_score', 100)}/100`",
                "",
                "| Vulnerability ID | Severity | Endpoint | Description | Recommended Fix |",
                "| :--- | :---: | :--- | :--- | :--- |"
            ])
            for f in sec_findings:
                md_lines.append(f"| `{f['id']}` | **{f['severity']}** | `{f['endpoint']}` | {f['title']} | {f['remediation']} |")
            md_lines.append("")

        markdown_doc = "\n".join(md_lines)

        # 2. Build Postman Collection v2.1.0
        postman_coll = self.snippet_generator.generate_postman_collection(title, endpoints, base_url)

        execution_time_ms = round((time.time() - start_time) * 1000, 2)
        state["documentation_markdown"] = markdown_doc
        state["postman_collection"] = postman_coll
        state["current_step"] = "doc_writing_completed"

        state["execution_log"].append({
            "agent": self.name,
            "action": "write_documentation_and_postman",
            "thought": f"Generated full Markdown developer guide ({len(endpoints)} endpoints with code samples) and Postman Collection v2.1.0.",
            "doc_length_chars": len(markdown_doc),
            "execution_time_ms": execution_time_ms
        })

        return state
