"""
Spec Generator Agent - Synthesizes OpenAPI 3.1.0 specification and JSON schemas.
Supports self-healing cycles when previous audit passes feedback.
Syllabus Alignment: Unit 2 (Specialist Agents, Handoffs) & Unit 3 (Agentic workflow in LangGraph).
"""

import time
from typing import Any, Dict, List
from .base_agent import BaseAgent


class SpecGeneratorAgent(BaseAgent):
    """Specialist agent responsible for producing standardized OpenAPI 3.1.0 specs."""

    def __init__(self, model_provider: str = "auto"):
        super().__init__(
            name="SpecGeneratorAgent",
            role="OpenAPI 3.1 Standards Engineer",
            goal="Synthesize flawless, complete OpenAPI 3.1.0 specifications and JSON schemas from extracted endpoints.",
            backstory="A developer experience architect adhering strictly to OpenAPI 3.1.0 and JSON Schema specifications.",
            tools=[],
            model_provider=model_provider
        )

    def execute(self, state: Dict[str, Any]) -> Dict[str, Any]:
        start_time = time.time()
        endpoints = state.get("endpoints", [])
        title = state.get("api_title", "RESTful API Service")
        version = state.get("api_version", "1.0.0")
        description = state.get("api_description", "Automated API documentation generated by Agentic AI Assistant.")
        feedback = state.get("audit_feedback", [])
        iteration = state.get("iteration_count", 0)

        # Build OpenAPI 3.1.0 Spec dictionary
        paths_obj: Dict[str, Any] = {}
        schemas_obj: Dict[str, Any] = {}
        has_auth_endpoint = False

        for ep in endpoints:
            path = ep.get("path", "/")
            method = ep.get("method", "GET").lower()
            summary = ep.get("summary", f"{method.upper()} {path}")
            ep_desc = ep.get("description", "")
            parameters = ep.get("parameters", [])
            request_body = ep.get("request_body")
            responses = ep.get("responses", {})
            auth_required = ep.get("auth_required", False)
            tags = ep.get("tags", ["General"])

            if auth_required:
                has_auth_endpoint = True

            # If self-healing detected missing path params, ensure they are present
            if feedback:
                for fb in feedback:
                    if "uses URL variables" in fb and path in fb:
                        # Auto-fix: ensure path parameter exists
                        path_vars = [p.get("name") for p in parameters if p.get("in") == "path"]
                        import re
                        for var in re.findall(r"\{([a-zA-Z0-9_]+)\}", path):
                            if var not in path_vars:
                                parameters.append({
                                    "name": var,
                                    "in": "path",
                                    "type": "string",
                                    "required": True,
                                    "description": f"Identifier for {var}"
                                })

            # Format parameters for OpenAPI
            openapi_params = []
            for p in parameters:
                p_in = p.get("in", "query")
                openapi_params.append({
                    "name": p.get("name", "param"),
                    "in": p_in,
                    "required": True if p_in == "path" else p.get("required", False),
                    "description": p.get("description", f"Parameter {p.get('name')}"),
                    "schema": {
                        "type": p.get("type", "string")
                    }
                })

            # Format responses
            openapi_responses: Dict[str, Any] = {}
            for code, resp in responses.items():
                openapi_responses[str(code)] = {
                    "description": resp.get("description", "Response"),
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": resp.get("fields", {"status": {"type": "string"}})
                            }
                        }
                    }
                }

            if not openapi_responses:
                openapi_responses["200"] = {
                    "description": "Successful operation",
                    "content": {"application/json": {"schema": {"type": "object"}}}
                }

            operation: Dict[str, Any] = {
                "summary": summary,
                "description": ep_desc,
                "operationId": ep.get("function_name") or f"{method}_{path.replace('/', '_').strip('_')}",
                "tags": tags,
                "parameters": openapi_params,
                "responses": openapi_responses
            }

            if auth_required:
                operation["security"] = [{"BearerAuth": []}]

            if request_body and method in ("post", "put", "patch"):
                schema_name = request_body.get("schema_name", "RequestBody")
                fields = request_body.get("fields", {})

                # Register in components.schemas
                schemas_obj[schema_name] = {
                    "type": "object",
                    "properties": {
                        f_name: {"type": f_info.get("type", "string")}
                        for f_name, f_info in fields.items()
                    } if fields else {"payload": {"type": "string"}}
                }

                operation["requestBody"] = {
                    "required": True,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": f"#/components/schemas/{schema_name}"
                            }
                        }
                    }
                }

            if path not in paths_obj:
                paths_obj[path] = {}
            paths_obj[path][method] = operation

        # Base Spec
        spec: Dict[str, Any] = {
            "openapi": "3.1.0",
            "info": {
                "title": title,
                "version": version,
                "description": description,
                "contact": {
                    "name": "API Support Team",
                    "email": "support@example.com"
                },
                "license": {
                    "name": "MIT",
                    "url": "https://opensource.org/licenses/MIT"
                }
            },
            "servers": [
                {"url": "https://api.production.company.com/v1", "description": "Production Server (HTTPS)"},
                {"url": "http://localhost:8000", "description": "Local Sandbox"}
            ],
            "paths": paths_obj,
            "components": {
                "schemas": schemas_obj,
                "securitySchemes": {
                    "BearerAuth": {
                        "type": "http",
                        "scheme": "bearer",
                        "bearerFormat": "JWT",
                        "description": "Standard JSON Web Token (JWT) Bearer header"
                    }
                } if has_auth_endpoint else {}
            }
        }

        execution_time_ms = round((time.time() - start_time) * 1000, 2)
        state["openapi_spec"] = spec
        state["current_step"] = "spec_generation_completed"
        thought = f"Synthesized OpenAPI 3.1.0 spec with {len(paths_obj)} paths and {len(schemas_obj)} schemas."
        if feedback:
            thought += f" Applied fixes for {len(feedback)} previous audit comments (Iteration {iteration})."

        state["execution_log"].append({
            "agent": self.name,
            "action": "generate_openapi_spec",
            "thought": thought,
            "iteration": iteration,
            "paths_count": len(paths_obj),
            "execution_time_ms": execution_time_ms
        })

        return state
